{% set name = "pdfnofonts" %}
{% set version = "1.1.0" %}
{% set sha256 = "b288330262666230d93af6aed93425e3838f58ab4103d01cbd8765a4361f42e3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/pdfnofonts/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pdfnofonts = pdfnofonts.cli.pdfnofonts:main

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - docopt
    - ghostscript

test:
  imports:
    - pdfnofonts
  commands:
    - pdfnofonts --help

about:
  home: https://github.com/tdegeus/pdfnofonts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Script to remove fonts from PDF file (wrapper around GhostScript).'
  description: 'Script to remove fonts from PDF file (wrapper around GhostScript).'
  doc_url: https://github.com/tdegeus/pdfnofonts
  dev_url: https://github.com/tdegeus/pdfnofonts

extra:
  recipe-maintainers:
    - tdegeus
