{% set name = "pdfnofonts" %}
{% set version = "1.0.1" %}
{% set sha256 = "9557aa15bca52fe53eaa24f73c191709e0061e2f5bbfef5bae3eabc0a6836b6e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/pdfnofonts/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - pdfnofonts = pdfnofonts:main

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - docopt
    - ghostscript

test:
  commands:
    - pdfnofonts --help

about:
  home: https://github.com/tdegeus/pdfnofonts
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Script of remove fonts from PDF file (wrapper around GhostScript).'
  description: 'Script of remove fonts from PDF file (wrapper around GhostScript).'
  doc_url: https://github.com/tdegeus/pdfnofonts
  dev_url: https://github.com/tdegeus/pdfnofonts

extra:
  recipe-maintainers:
    - tdegeus
